try{
    console.log('試し実行開始');

    console.log('試し実行終了')
}catch(err){
    console.log('エラーがないため無視します。');
}